### ISSUE TITLE
Address Sanitizer instrumented VNCViewer aborts with heap-buffer-overflow

### ISSUE THREAD

**Issue by williamsjoblom** [TigerVNC/tigervnc#1395]
**Describe the bug**
If I run an ASan instrumented vncviewer, ASan aborts with a heap-buffer-overflow error whenever I click "Connect" or "Options...". I have not spent any time investigating this further, nonetheless, this error should probably be fixed (or suppressed with a `__attribute__((no_sanitize_address))` if it proves to be a false positive) as being able to use ASan without it aborting right away is generally useful.

**To Reproduce**
1. `cd tigervnc`
2. `cmake -DCMAKE_CXX_FLAGS='-fsanitize=address' -DCMAKE_C_FLAGS='-fsanitize=address' .`
3. `make vncviewer`
4. `vncviewer/vncviewer`
5. Press "Options..."

**Expected behavior**
That no such ASan abort happens and the client continues running normally.

**Client (please complete the following information):**
 - OS: Fedora 34
 - VNC client: TigerVNC
 - VNC client version: built from master at 2b25d837e

**ASan Output**
```
[31:10] ➜  /l/h/w/tigervnc vncviewer/vncviewer

TigerVNC Viewer 64-bit v1.12.80
Built on: 2021-12-13 10:07
Copyright (C) 1999-2021 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
=================================================================
==725339==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300005aa14 at pc 0x000000470437 bp 0x7ffe5f17b450 sp 0x7ffe5f17b448
READ of size 4 at 0x60300005aa14 thread T0
    #0 0x470436 in MonitorIndicesParameter::fetchMonitors() (/local/home/wilsj/tigervnc/vncviewer/vncviewer+0x470436)
    #1 0x4707f7 in MonitorIndicesParameter::getParam() (/local/home/wilsj/tigervnc/vncviewer/vncviewer+0x4707f7)
    #2 0x44cc6b in OptionsDialog::loadOptions() (/local/home/wilsj/tigervnc/vncviewer/vncviewer+0x44cc6b)
    #3 0x44e36b in OptionsDialog::showDialog() (/local/home/wilsj/tigervnc/vncviewer/vncviewer+0x44e36b)
    #4 0x7efd15682c34 in Fl_Widget::do_callback(Fl_Widget*, void*) (/lib64/libfltk.so.1.3+0xb3c34)
    #5 0x7efd15630117 in Fl_Button::handle(int) (/lib64/libfltk.so.1.3+0x61117)
    #6 0x7efd15623ca2 in send_event(int, Fl_Widget*, Fl_Window*) (/lib64/libfltk.so.1.3+0x54ca2)
    #7 0x7efd1562669d in Fl::handle_(int, Fl_Window*) (/lib64/libfltk.so.1.3+0x5769d)
    #8 0x7efd1568fbe1 in fl_handle(_XEvent const&) (/lib64/libfltk.so.1.3+0xc0be1)
    #9 0x7efd156823d1 in do_queued_events() (/lib64/libfltk.so.1.3+0xb33d1)
    #10 0x7efd15682739 in fl_wait(double) (/lib64/libfltk.so.1.3+0xb3739)
    #11 0x7efd15625d58 in Fl::wait(double) (/lib64/libfltk.so.1.3+0x56d58)
    #12 0x7efd15625e60 in Fl::wait() (/lib64/libfltk.so.1.3+0x56e60)
    #13 0x4413d4 in ServerDialog::run(char const*, char*) (/local/home/wilsj/tigervnc/vncviewer/vncviewer+0x4413d4)
    #14 0x41d411 in main (/local/home/wilsj/tigervnc/vncviewer/vncviewer+0x41d411)
    #15 0x7efd14ae3b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)
    #16 0x41f9ed in _start (/local/home/wilsj/tigervnc/vncviewer/vncviewer+0x41f9ed)

0x60300005aa14 is located 0 bytes to the right of 20-byte region [0x60300005aa00,0x60300005aa14)
allocated by thread T0 here:
    #0 0x7efd157cc0a7 in operator new(unsigned long) (/lib64/libasan.so.6+0xb00a7)
    #1 0x473224 in void std::vector<MonitorIndicesParameter::Monitor, std::allocator<MonitorIndicesParameter::Monitor> >::_M_realloc_insert<MonitorIndicesParameter::Monitor const&>(__gnu_cxx::__normal_iterator<MonitorIndicesParameter::Monitor*, std::vector<MonitorIndicesParameter::Monitor, std::allocator<MonitorIndicesParameter::Monitor> > >, MonitorIndicesParameter::Monitor const&) (/local/home/wilsj/tigervnc/vncviewer/vncviewer+0x473224)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/local/home/wilsj/tigervnc/vncviewer/vncviewer+0x470436) in MonitorIndicesParameter::fetchMonitors()
Shadow bytes around the buggy address:
  0x0c06800034f0: fa fa fd fd fd fa fa fa fd fd fd fa fa fa 00 00
  0x0c0680003500: 00 fa fa fa 00 00 00 fa fa fa 00 00 00 fa fa fa
  0x0c0680003510: fd fd fd fa fa fa fd fd fd fa fa fa fd fd fd fa
  0x0c0680003520: fa fa 00 00 00 fa fa fa 00 00 00 fa fa fa 00 00
  0x0c0680003530: 00 fa fa fa 00 00 00 05 fa fa 00 00 00 06 fa fa
=>0x0c0680003540: 00 00[04]fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0680003550: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0680003560: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0680003570: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0680003580: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0680003590: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==725339==ABORTING
```

**Comment by CendioOssman** [comment]
Fixed in 2daf4126882f82b6e392dfbae87205dbdc559c3d.
