### ISSUE TITLE
Can not input content on AWT textbox (cursor missing) 

### ISSUE THREAD

**Issue by happylinda** [TigerVNC/tigervnc#287]
Hi,

When I use tigervnc, I run into following error
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Failed to retrieve atom name.
	at sun.awt.X11.XlibWrapper.XGetAtomName(Native Method)
	at sun.awt.X11.XAtom.getName(XAtom.java:198)

Could you help to give me some suggestion? I'm not sure that It's my configuration issue or tigervnc defect.

**Comment by bphinz** [comment]
Can you provide a little more detail (OS, JRE, how to replicate the problem, etc.)?

-brian

**Comment by happylinda** [comment]
Thanks for your quick feedback.

I tried to use TigerVNC work with xrdp. 
My environment is as below,
Ubuntn: 15.10
JRE: 1.7.0
xrdp: 0.6.1

I used mstsc to connect my Ubuntn server with "sesman-Xvnc" module, my application (created in java) run into this error.

**Comment by CendioOssman** [comment]
I'm sorry, but where does TigerVNC get involved in this if you are using mstsc and xrdp?

And is the exception from our viewer? Or some other Java application?

**Comment by hildred** [comment]
xrdp is a rdp to rfb translator, It does not have a Xserver but uses Xvnc instead.

**Comment by CendioOssman** [comment]
Ah, I see. Thanks.

So I then assume that the crash here is some random application and not our Java viewer? And looking at the error, it looks like that program is not handling missing atoms properly. Which would most likely be a bug in that program rather than TigerVNC. @happylinda, can you determine which atom it is trying to look up?

**Comment by happylinda** [comment]
The exception is from our Java application, it is related with copy/paste operation. The detail exception is as below,
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Failed to retrieve atom name.
        at sun.awt.X11.XlibWrapper.XGetAtomName(Native Method)
        at sun.awt.X11.XAtom.getName(XAtom.java:198)
        at sun.awt.X11.XDataTransferer.getTargetNameForAtom(XDataTransferer.java:177)
        at sun.awt.X11.XDataTransferer.getNativeForFormat(XDataTransferer.java:166)
        at sun.awt.datatransfer.DataTransferer.getFlavorsForFormats(DataTransferer.java:748)
        at sun.awt.datatransfer.ClipboardTransferable.<init>(ClipboardTransferable.java:102)
        at sun.awt.X11.XClipboard.getContents(XClipboard.java:120)
        at javax.swing.TransferHandler$TransferAction.actionPerformedImpl(TransferHandler.java:1766)
        at javax.swing.TransferHandler$TransferAction.access$800(TransferHandler.java:1703)
        at javax.swing.TransferHandler$TransferAction$1.run(TransferHandler.java:1726)
        at javax.swing.TransferHandler$TransferAction$1.run(TransferHandler.java:1724)
        at java.security.AccessController.doPrivileged(AccessController.java:620)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at javax.swing.TransferHandler$TransferAction$2.run(TransferHandler.java:1741)
        at javax.swing.TransferHandler$TransferAction$2.run(TransferHandler.java:1739)
        at java.security.AccessController.doPrivileged(AccessController.java:620)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at javax.swing.TransferHandler$TransferAction.actionPerformed(TransferHandler.java:1738)
        at javax.swing.text.JTextComponent.invokeAction(JTextComponent.java:1473)
        at javax.swing.text.JTextComponent.paste(JTextComponent.java:1451)
        at javax.swing.text.DefaultEditorKit$PasteAction.actionPerformed(DefaultEditorKit.java:1442)
        at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1674)
        at javax.swing.JComponent.processKeyBinding(JComponent.java:2893)
        at javax.swing.JComponent.processKeyBindings(JComponent.java:2940)
        at javax.swing.JComponent.processKeyEvent(JComponent.java:2856)
        at java.awt.Component.processEvent(Component.java:6323)
        at java.awt.Container.processEvent(Container.java:2247)
        at java.awt.Component.dispatchEventImpl(Component.java:4902)
        at java.awt.Container.dispatchEventImpl(Container.java:2305)
        at java.awt.Component.dispatchEvent(Component.java:4724)
        at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1965)
        at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:817)
        at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1085)
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:956)
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:782)
        at java.awt.Component.dispatchEventImpl(Component.java:4773)
        at java.awt.Container.dispatchEventImpl(Container.java:2305)
        at java.awt.Window.dispatchEventImpl(Window.java:2761)
        at java.awt.Component.dispatchEvent(Component.java:4724)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:769)
        at java.awt.EventQueue.access$500(EventQueue.java:108)
        at java.awt.EventQueue$3.run(EventQueue.java:720)
        at java.awt.EventQueue$3.run(EventQueue.java:714)
        at java.security.AccessController.doPrivileged(AccessController.java:620)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.awt.EventQueue$4.run(EventQueue.java:742)
        at java.awt.EventQueue$4.run(EventQueue.java:740)
        at java.security.AccessController.doPrivileged(AccessController.java:620)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:739)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:212)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:127)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:112)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:104)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:93)

It seems that it is X related Java problem. I see the following JRE bug fixed.
[http://bugs.java.com/view_bug.do?bug_id=8043393](url)
 
I also see the following suggestion of switching the clipboard manager to workaround the issue:
[http://www.skybert.net/java/x-related-java-problems/](url)

It seems that it is not related with TigerVNC. Thanks for your help.
