### ISSUE TITLE
TightDecoder: Too Large Rectangle

### ISSUE THREAD

**Issue by arantius** [TigerVNC/tigervnc#595]
I downloaded the java client today, and attempted to connect to a VNC viewer (via SSH tunneling, so localhost):

    $ java -jar ~/Downloads/VncViewer-1.8.0.jar 
    
    TigerVNC Java Viewer v1.8.0 (20170517)
    Built on May 17 2017 at 20:39:19
    Copyright (C) 1999-2017 TigerVNC Team and many others (see README.txt)
    See http://www.tigervnc.org for information on TigerVNC.
    DecodeManager: Detected 12 CPU core(s)
    DecodeManager: Creating 4 decoder thread(s)
    CConn: connected to host localhost port 5900
    CConnection: Server supports RFB protocol version 3.8
    CConnection: Using RFB protocol version 3.8
    CConn: Using pixel format depth 24 (32bpp) little-endian rgb888
    CConn: Using Tight encoding
    com.tigervnc.rfb.Exception: TightDecoder: too large rectangle (3600 pixels)
            at com.tigervnc.rfb.TightDecoder.readRect(TightDecoder.java:99)
            at com.tigervnc.rfb.DecodeManager.decodeRect(DecodeManager.java:135)
            at com.tigervnc.rfb.CConnection.dataRect(CConnection.java:364)
            at com.tigervnc.vncviewer.CConn.dataRect(CConn.java:431)
            at com.tigervnc.rfb.CMsgReader.readRect(CMsgReader.java:209)
            at com.tigervnc.rfb.CMsgReader.readMsg(CMsgReader.java:121)
            at com.tigervnc.rfb.CConnection.processMsg(CConnection.java:136)
            at com.tigervnc.vncviewer.VncViewer.run(VncViewer.java:538)
            at java.lang.Thread.run(Thread.java:745)

The server side is a dual-monitor setup, one at 1920x1200 next to the other at 1680x1050 -- it is indeed 3600 pixels wide.  If I force hextile I can connect, but I get a window larger than my current screen, with no scroll bars unless I manually resize the window down.

If I use the TightVNC java client, the console output includes the lines:

    Desktop size is 3600 x 1200
    Using Tight/ZRLE encodings
    Throughput 19858 kbit/s - changing to Hextile encoding

But I can force it to use Tight only, and it works.

**Comment by bphinz** [comment]
Can you please try the latest nightly build (http://tigervnc.bphinz.com/nightly/) and see if you can reproduce this?  I just fixed several decoder errors a few weeks ago.

**Comment by arantius** [comment]
Nightly works!  But still makes a window bigger than my screen.
