### ISSUE TITLE
x0vncserver crashes (SIGSEGV) on client disconnect

### ISSUE THREAD

**Issue by streamer45** [TigerVNC/tigervnc#644]
Hi, I am getting a crash (SIGSEGV) everytime a client disconnects after a successful connection.

I am currently running TigerVNC Server version 1.8.0 on Arch Linux x86_64 kernel 4.16.7-1-ARCH #1 SMP PREEMPT 

X.Org X Server 1.19.6
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.15.6-1-ARCH x86_64

Here are some debugging logs which might be helpful:

```
[system@test2 ~]$ gdb x0vncserver
GNU gdb (GDB) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from x0vncserver...(no debugging symbols found)...done.
(gdb) run -display :0 -geometry 1280x1024 -framerate 30 -passwordfile pwd
Starting program: /usr/bin/x0vncserver -display :0 -geometry 1280x1024 -framerate 30 -passwordfile pwd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Wed May 16 09:50:10 2018
 Geometry:    Desktop geometry is set to 1280x1024+0+0
 Main:        XTest extension present - version 2.2
 Main:        Listening on port 5900

Wed May 16 09:50:16 2018
 Connections: accepted: [::1]::36754

Wed May 16 09:50:17 2018
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)
 Main:        Enabling 8 buttons of X pointer device
 Main:        Allocated basic Xlib image
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
 VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian rgb888

Wed May 16 09:50:22 2018
 Connections: closed: [::1]::36754 (Clean disconnection)
 EncodeManager: Framebuffer updates: 28
 EncodeManager:   Tight (JPEG):
 EncodeManager:     Full Colour: 588 rects, 36.7002 Mpixels
 EncodeManager:                  4.40381 MiB (1:31.7922 ratio)
 EncodeManager:   Total: 588 rects, 36.7002 Mpixels
 EncodeManager:          4.40381 MiB (1:31.7922 ratio)
 ComparingUpdateTracker: 77.3325 Mpixels in / 77.3325 Mpixels out
 ComparingUpdateTracker: (1:1 ratio)

Program received signal SIGSEGV, Segmentation fault.
0x000055555599dd30 in ?? ()
(gdb) backtrace 
#0  0x000055555599dd30 in ?? ()
#1  0x000055555558c276 in rfb::VNCServerST::writeUpdate() ()
#2  0x000055555558c3f9 in non-virtual thunk to rfb::VNCServerST::handleTimeout(rfb::Timer*) ()
#3  0x00005555555899e1 in rfb::Timer::checkTimeouts() ()
#4  0x000055555558a658 in rfb::VNCServerST::checkTimeouts() ()
#5  0x0000555555577562 in main ()
```

```
[system@test2 ~]$ valgrind /usr/bin/x0vncserver -display :0 -geometry 1280x1024 -framerate 30 -passwordfile pwd
==32536== Memcheck, a memory error detector
==32536== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==32536== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==32536== Command: /usr/bin/x0vncserver -display :0 -geometry 1280x1024 -framerate 30 -passwordfile pwd
==32536== 

Wed May 16 09:44:33 2018
 Geometry:    Desktop geometry is set to 1280x1024+0+0
 Main:        XTest extension present - version 2.2
 Main:        Listening on port 5900

Wed May 16 09:44:42 2018
 Connections: accepted: [::1]::36734
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)
 Main:        Enabling 8 buttons of X pointer device

Wed May 16 09:44:44 2018
 Main:        Allocated basic Xlib image
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888

Wed May 16 09:44:47 2018
 VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian rgb888

Wed May 16 09:45:02 2018
 Connections: closed: [::1]::36734 (write: Broken pipe (32))
 EncodeManager: Framebuffer updates: 5
 EncodeManager:   Tight (JPEG):
 EncodeManager:     Full Colour: 93 rects, 5.8304 Mpixels
 EncodeManager:                  716.531 KiB (1:31.7866 ratio)
 EncodeManager:   Total: 93 rects, 5.8304 Mpixels
 EncodeManager:          716.531 KiB (1:31.7866 ratio)
 ComparingUpdateTracker: 7.86432 Mpixels in / 7.86432 Mpixels out
 ComparingUpdateTracker: (1:1 ratio)
==32536== Invalid read of size 4
==32536==    at 0x13FF75: rfb::VNCServerST::writeUpdate() (in /usr/bin/x0vncserver)
==32536==    by 0x1403F8: non-virtual thunk to rfb::VNCServerST::handleTimeout(rfb::Timer*) (in /usr/bin/x0vncserver)
==32536==    by 0x13D9E0: rfb::Timer::checkTimeouts() (in /usr/bin/x0vncserver)
==32536==    by 0x13E657: rfb::VNCServerST::checkTimeouts() (in /usr/bin/x0vncserver)
==32536==    by 0x12B44D: main (in /usr/bin/x0vncserver)
==32536==  Address 0x90d2344 is 68 bytes inside a block of size 128 free'd
==32536==    at 0x4C2E60B: operator delete(void*) (vg_replace_malloc.c:576)
==32536==    by 0x12F5EC: XDesktop::stop() (in /usr/bin/x0vncserver)
==32536==    by 0x13EBE4: rfb::VNCServerST::removeSocket(network::Socket*) (in /usr/bin/x0vncserver)
==32536==    by 0x12B398: main (in /usr/bin/x0vncserver)
==32536==  Block was alloc'd at
==32536==    at 0x4C2D54F: operator new(unsigned long) (vg_replace_malloc.c:334)
==32536==    by 0x12FCFF: XDesktop::start(rfb::VNCServer*) (in /usr/bin/x0vncserver)
==32536==    by 0x13EA4B: rfb::VNCServerST::startDesktop() (in /usr/bin/x0vncserver)
==32536==    by 0x14FF9A: rfb::VNCSConnectionST::authSuccess() (in /usr/bin/x0vncserver)
==32536==    by 0x14E95F: rfb::VNCSConnectionST::queryConnection(char const*) (in /usr/bin/x0vncserver)
==32536==    by 0x145677: rfb::SConnection::processSecurityMsg() (in /usr/bin/x0vncserver)
==32536==    by 0x150B87: rfb::VNCSConnectionST::processMessages() (in /usr/bin/x0vncserver)
==32536==    by 0x12B5DD: main (in /usr/bin/x0vncserver)
==32536== 
==32536== Invalid read of size 4
==32536==    at 0x13FF78: rfb::VNCServerST::writeUpdate() (in /usr/bin/x0vncserver)
==32536==    by 0x1403F8: non-virtual thunk to rfb::VNCServerST::handleTimeout(rfb::Timer*) (in /usr/bin/x0vncserver)
==32536==    by 0x13D9E0: rfb::Timer::checkTimeouts() (in /usr/bin/x0vncserver)
==32536==    by 0x13E657: rfb::VNCServerST::checkTimeouts() (in /usr/bin/x0vncserver)
==32536==    by 0x12B44D: main (in /usr/bin/x0vncserver)
==32536==  Address 0x90d2348 is 72 bytes inside a block of size 128 free'd
==32536==    at 0x4C2E60B: operator delete(void*) (vg_replace_malloc.c:576)
==32536==    by 0x12F5EC: XDesktop::stop() (in /usr/bin/x0vncserver)
==32536==    by 0x13EBE4: rfb::VNCServerST::removeSocket(network::Socket*) (in /usr/bin/x0vncserver)
==32536==    by 0x12B398: main (in /usr/bin/x0vncserver)
==32536==  Block was alloc'd at
==32536==    at 0x4C2D54F: operator new(unsigned long) (vg_replace_malloc.c:334)
==32536==    by 0x12FCFF: XDesktop::start(rfb::VNCServer*) (in /usr/bin/x0vncserver)
==32536==    by 0x13EA4B: rfb::VNCServerST::startDesktop() (in /usr/bin/x0vncserver)
==32536==    by 0x14FF9A: rfb::VNCSConnectionST::authSuccess() (in /usr/bin/x0vncserver)
==32536==    by 0x14E95F: rfb::VNCSConnectionST::queryConnection(char const*) (in /usr/bin/x0vncserver)
==32536==    by 0x145677: rfb::SConnection::processSecurityMsg() (in /usr/bin/x0vncserver)
==32536==    by 0x150B87: rfb::VNCSConnectionST::processMessages() (in /usr/bin/x0vncserver)
==32536==    by 0x12B5DD: main (in /usr/bin/x0vncserver)
==32536== 
==32536== Invalid read of size 8
==32536==    at 0x1400C3: rfb::VNCServerST::writeUpdate() (in /usr/bin/x0vncserver)
==32536==    by 0x1403F8: non-virtual thunk to rfb::VNCServerST::handleTimeout(rfb::Timer*) (in /usr/bin/x0vncserver)
==32536==    by 0x13D9E0: rfb::Timer::checkTimeouts() (in /usr/bin/x0vncserver)
==32536==    by 0x13E657: rfb::VNCServerST::checkTimeouts() (in /usr/bin/x0vncserver)
==32536==    by 0x12B44D: main (in /usr/bin/x0vncserver)
==32536==  Address 0x90d2300 is 0 bytes inside a block of size 128 free'd
==32536==    at 0x4C2E60B: operator delete(void*) (vg_replace_malloc.c:576)
==32536==    by 0x12F5EC: XDesktop::stop() (in /usr/bin/x0vncserver)
==32536==    by 0x13EBE4: rfb::VNCServerST::removeSocket(network::Socket*) (in /usr/bin/x0vncserver)
==32536==    by 0x12B398: main (in /usr/bin/x0vncserver)
==32536==  Block was alloc'd at
==32536==    at 0x4C2D54F: operator new(unsigned long) (vg_replace_malloc.c:334)
==32536==    by 0x12FCFF: XDesktop::start(rfb::VNCServer*) (in /usr/bin/x0vncserver)
==32536==    by 0x13EA4B: rfb::VNCServerST::startDesktop() (in /usr/bin/x0vncserver)
==32536==    by 0x14FF9A: rfb::VNCSConnectionST::authSuccess() (in /usr/bin/x0vncserver)
==32536==    by 0x14E95F: rfb::VNCSConnectionST::queryConnection(char const*) (in /usr/bin/x0vncserver)
==32536==    by 0x145677: rfb::SConnection::processSecurityMsg() (in /usr/bin/x0vncserver)
==32536==    by 0x150B87: rfb::VNCSConnectionST::processMessages() (in /usr/bin/x0vncserver)
==32536==    by 0x12B5DD: main (in /usr/bin/x0vncserver)
==32536== 
^C
Wed May 16 09:48:09 2018
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:-nan ratio)
X Error of failed request:  BadDamage (invalid Damage parameter)
  Major opcode of failed request:  143 (DAMAGE)
  Minor opcode of failed request:  2 (XDamageDestroy)
  Serial number of failed request:  58
  Current serial number in output stream:  58
==32536== 
==32536== HEAP SUMMARY:
==32536==     in use at exit: 156,478 bytes in 1,714 blocks
==32536==   total heap usage: 12,008 allocs, 10,294 frees, 101,809,217 bytes allocated
==32536== 
==32536== LEAK SUMMARY:
==32536==    definitely lost: 64 bytes in 2 blocks
==32536==    indirectly lost: 76 bytes in 1 blocks
==32536==      possibly lost: 0 bytes in 0 blocks
==32536==    still reachable: 156,338 bytes in 1,711 blocks
==32536==         suppressed: 0 bytes in 0 blocks
==32536== Rerun with --leak-check=full to see details of leaked memory
==32536== 
==32536== For counts of detected and suppressed errors, rerun with: -v
==32536== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
```

**Comment by CendioOssman** [comment]
This was fixed as part of #515 and will be included in the next release. Please try a nightly build until then.
