### ISSUE TITLE
Java viewer hangs upon connecting to server, before asking for username,  [when using TLS]

### ISSUE THREAD

**Issue by imperative** [TigerVNC/tigervnc#771]
Starting a server with this line:
`x0vncserver -display :0  -SecurityTypes X509Vnc -X509Cert /etc/ssl/certs/ssl-cert-snakeoil.pem -X509Key /etc/ssl/private/ssl-cert-snakeoil.key -passwordfile /root/.vnc/passwd`

When trying to connect with latest (1.9.0) Java viewer, after entering the server address and clicking [Connect], the viewer connection window dissapears, nothing else appears, and the application hangs.

The following logs are displayed:
SERVER:

```
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VeNCrypt(19)
 SVeNCrypt:   Client requests security type X509Vnc (261)
```

CLIENT:
```
CConnection: Server supports RFB protocol version 3.8
CConnection: Using RFB protocol version 3.8
Exception in thread "VncViewer Thread" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.tigervnc.rfb.CSecurityTLS$MyX509TrustManager.getThumbprint(CSecurityTLS.java:348)
	at com.tigervnc.rfb.CSecurityTLS$MyX509TrustManager.<init>(CSecurityTLS.java:217)
	at com.tigervnc.rfb.CSecurityTLS.setParam(CSecurityTLS.java:163)
	at com.tigervnc.rfb.CSecurityTLS.processMsg(CSecurityTLS.java:138)
	at com.tigervnc.rfb.CSecurityStack.processMsg(CSecurityStack.java:41)
	at com.tigervnc.rfb.CSecurityVeNCrypt.processMsg(CSecurityVeNCrypt.java:177)
	at com.tigervnc.rfb.CConnection.processSecurityMsg(CConnection.java:263)
	at com.tigervnc.rfb.CConnection.processMsg(CConnection.java:133)
	at com.tigervnc.vncviewer.VncViewer.run(VncViewer.java:565)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 10 more

```

**Comment by bphinz** [comment]
Can you tell me what version of Java you are using?

**Comment by bphinz** [comment]
If you are using Java 9 or 10 then adding "--add-modules java.xml.bind" to your JVM command line args is supposed to be a workaround.  That's not viable for Java 11+ however.

**Comment by imperative** [comment]
Adding "--add-modules java.xml.bind" helped and it now connects properly, thank you!
I think this should of course still be built-in in the future.

**Comment by bphinz** [comment]
> I think this should of course still be built-in in the future.

Agreed.  I have some code that should work for Java 9+, I just need to test it out and then I'll commit it
