### ISSUE TITLE
TurboVNC server  (2.2.1-20190102) on centos 7 with tiger vncviewer 1.9 connection reset by peer when changing window size 

### ISSUE THREAD

**Issue by janor666** [TigerVNC/tigervnc#833]
Hello, we have a centos 7 server with TurboVnc server (2.2.1-20190102). When some clients connects with TigerVnc 1.9 (vncviewer-1.9.0.exe) and resizing the windows the connection closes. (connection reset by peer) (readTLS)(unknown error code)

/.vnc/*.log

10/05/2019 09:04:54 Got connection from client xx.xx.xx.xx
10/05/2019 09:04:54 Using protocol version 3.8
10/05/2019 09:04:54 Enabling VeNCrypt protocol extensions
10/05/2019 09:04:54 Client requested VeNCrypt sub-type 258
10/05/2019 09:04:54 Deferring TLS handshake
10/05/2019 09:04:59 Full-control authentication enabled for 
10/05/2019 09:04:59 Pixel format for client 
10/05/2019 09:04:59   32 bpp, depth 24, little endian
10/05/2019 09:04:59   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
10/05/2019 09:04:59   no translation needed
10/05/2019 09:04:59 rfbProcessClientNormalMessage: ignoring unknown encoding -314 (fffffec6)
10/05/2019 09:04:59 Enabling full-color cursor updates for client 
10/05/2019 09:04:59 Enabling Desktop Size protocol extension for client 
10/05/2019 09:04:59 Enabling Extended Desktop Size protocol extension for client 
10/05/2019 09:04:59 rfbProcessClientNormalMessage: ignoring unknown encoding -307 (fffffecd)
10/05/2019 09:04:59 rfbProcessClientNormalMessage: ignoring unknown encoding -261 (fffffefb)
10/05/2019 09:04:59 Enabling LastRect protocol extension for client 
10/05/2019 09:04:59 Enabling Continuous Updates protocol extension for client 
10/05/2019 09:04:59 Enabling Fence protocol extension for client 
10/05/2019 09:04:59 rfbProcessClientNormalMessage: ignoring unknown encoding -258 (fffffefe)
10/05/2019 09:04:59 Using tight encoding for client 
10/05/2019 09:04:59 Using JPEG subsampling 0, Q92 for client 
10/05/2019 09:04:59 Using 4 threads for Tight encoding
10/05/2019 09:04:59 New desktop size: 1674 x 1017
10/05/2019 09:04:59 New screen layout:
10/05/2019 09:04:59   0x00000029 (output 0x00000040): 1674x1017+0+0
10/05/2019 09:04:59 rfbProcessClientNormalMessage: read: Connection reset by peer
10/05/2019 09:04:59 Client xx.xx.xx.xx gone
10/05/2019 09:04:59 Statistics:
10/05/2019 09:04:59   framebuffer updates 1, rectangles 74, bytes 929887
10/05/2019 09:04:59     LastRect markers 1, bytes 12
10/05/2019 09:04:59     cursor shape updates 1, bytes 2388
10/05/2019 09:04:59     Tight rectangles 72, bytes 927487
10/05/2019 09:04:59   raw equivalent 7.056012 Mbytes, compression ratio 7.607667

**Comment by CendioOssman** [comment]
That error code generally only happens when the applications crashes. Are you getting any crash dialogs on the client machines?

Do you have access to a Linux client for testing? It would probably be easier to debug things there.

**Comment by janor666** [comment]
The actual error is readTLS: Decryption has failed. (-24). But we had also Errors like readTLS:(uknown error code)(91707840)
I'm sorry to say that I have no possibilty to test with a Linux client.

**Comment by janor666** [comment]
We also tried to change the server side to TigerVNC, but on some clients (Windows 7 vncviwer 1.9) we get TLS Erros as well than.

Thu May  9 14:23:29 2019
 Connections: accepted: xx.xx.xx.xx::61082
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VeNCrypt(19)
 SVeNCrypt:   Client requests security type TLSVnc (258)

Thu May  9 14:23:32 2019
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
 VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian rgb888

Thu May  9 15:10:03 2019
 ComparingUpdateTracker: 758.737 Mpixels in / 141.656 Mpixels out
 ComparingUpdateTracker: (1:5.3562 ratio)

Thu May  9 15:10:20 2019
 ComparingUpdateTracker: 6.91651 Mpixels in / 2.83527 Mpixels out
 ComparingUpdateTracker: (1:2.43945 ratio)

Thu May  9 15:37:55 2019
 Connections: closed: 10.192.122.146::61082 (Clean disconnection)
 EncodeManager: Framebuffer updates: 4249
 EncodeManager:   CopyRect:
 EncodeManager:     Copies: 1 rects, 339.108 kpixels
 EncodeManager:             16 B (1:84777.8 ratio)
 EncodeManager:   Tight:
 EncodeManager:     Solid: 19.997 krects, 137.984 Mpixels
 EncodeManager:            312.453 KiB (1:1725.81 ratio)
 EncodeManager:     Bitmap RLE: 1.36 krects, 643.88 kpixels
 EncodeManager:                 41.0244 KiB (1:61.6973 ratio)
 EncodeManager:     Indexed RLE: 10.786 krects, 15.4683 Mpixels
 EncodeManager:                  2.10601 MiB (1:28.0769 ratio)
 EncodeManager:   Tight (JPEG):
 EncodeManager:     Full Colour: 13.652 krects, 158.691 Mpixels
 EncodeManager:                  95.1139 MiB (1:6.3662 ratio)
 EncodeManager:   Total: 45.796 krects, 313.126 Mpixels
 EncodeManager:          97.5652 MiB (1:12.2483 ratio)
 TLS:         TLS session wasn't terminated gracefully
 ComparingUpdateTracker: 799.08 Mpixels in / 174.158 Mpixels out
 ComparingUpdateTracker: (1:4.58825 ratio)

**Comment by CendioOssman** [comment]
Let's continue testing with a TigerVNC server then, as it makes it easier for us to debug.

Where did you get the client and server? Downloaded from our bintray repo?

**Comment by janor666** [comment]
TigerVnc Server we got from yum install tigervnc on centos7. 
In the log the version is mentioned at the start.

"Xvnc TigerVNC 1.8.0 - built Nov  2 2018 19:05:14
Copyright (C) 1999-2017 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12001000, The X.Org Foundation"

For the client we use vncviewer64-1.7.1.exe or vncviewer-1.9.0.exe from your bintray. 
We are just trying to not use TLS and not use auto select in the VNC Viewer options. We are just testing this options on two windows clients today. We now use hextile as encoding option. 

One of the new errors when we disabled TLS was "rect too big" which was mentioned here:
https://superuser.com/questions/156910/stop-vnc-from-rect-too-big

**Comment by CendioOssman** [comment]
I just tried that exact setup without any issues.

What devices are you seeing this on? Are they perhaps rather old? I wonder if there is a CPU instruction issue.

**Comment by janor666** [comment]
They are not very old. I think at max 2-3 years old. With the options (no tls and no auto select) one user send me the errors he gets clientside: "Rect too big" and "uknown message type".

Serverside the error is:

 Connections: closed: xx.xx.xx.xx::50645 (read: Connection reset by peer
              (104))
 Connections: closed: xx.xx.xx.xx::50644 (write: Connection reset by peer
              (104))

full log:

Wed May 15 11:18:28 2019
 Connections: accepted: :xx.xx.xx.xx:50645
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VeNCrypt(19)
 SVeNCrypt:   Client requests security type VncAuth (2)

Wed May 15 11:18:33 2019
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
 VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian rgb888

Wed May 15 11:19:19 2019
 Connections: closed: xx.xx.xx.xx::50645 (read: Connection reset by peer
              (104))
 EncodeManager: Framebuffer updates: 142
 EncodeManager:   CopyRect:
 EncodeManager:     Copies: 7 rects, 1.1651 Mpixels
 EncodeManager:             112 B (1:41611.4 ratio)
 EncodeManager:   Hextile:
 EncodeManager:     Bitmap RLE: 129 rects, 89.819 kpixels
 EncodeManager:                 5.84766 KiB (1:60.2578 ratio)
 EncodeManager:     Indexed RLE: 239 rects, 2.06845 Mpixels
 EncodeManager:                  264.152 KiB (1:30.5985 ratio)
 EncodeManager:     Full Colour: 381 rects, 5.72421 Mpixels
 EncodeManager:                  4.84618 MiB (1:4.50674 ratio)
 EncodeManager:   Tight:
 EncodeManager:     Solid: 318 rects, 4.5881 Mpixels
 EncodeManager:            4.96875 KiB (1:3607.75 ratio)
 EncodeManager:   Total: 1.074 krects, 13.6357 Mpixels
 EncodeManager:          5.11481 MiB (1:10.1721 ratio)
 ComparingUpdateTracker: 36.5429 Mpixels in / 10.8853 Mpixels out
 ComparingUpdateTracker: (1:3.35708 ratio)

**Comment by janor666** [comment]
We could try the VncViewer-1.9.0.jar running in a CMD shell with java -jar. So we get more detailed errors?

**Comment by janor666** [comment]
TigerVNC Java Viewer v1.9.0 (20180718)
Built on Jul 18 2018 at 22:10:07
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org for information on TigerVNC.
DecodeManager: Detected 4 CPU core(s)
DecodeManager: Creating 4 decoder thread(s)
CConn: connected to host xxx port 5903
CConnection: Server supports RFB protocol version 3.8
CConnection: Using RFB protocol version 3.8
CConn: Using pixel format depth 24 (32bpp) little-endian rgb888
CConn: Using Tight encoding
CConn: Enabling continuous updates
VncTransferHandler: java.awt.datatransfer.UnsupportedFlavorException: Unicode String
VncTransferHandler: java.awt.datatransfer.UnsupportedFlavorException: Unicode String

**Comment by CendioOssman** [comment]
Those errors are very concerning. It suggests that the data is being corrupted somehow. Do you have a firewall or proxy or some other equipment on your network that might be interfering with the data?

**Comment by janor666** [comment]
We have a firewall, but turning it off does not resolve the issue. Another exception is:

TigerVNC Java Viewer v1.9.0 (20180718)
Built on Jul 18 2018 at 22:10:07
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org for information on TigerVNC.
DecodeManager: Detected 4 CPU core(s)
DecodeManager: Creating 4 decoder thread(s)
CConn: connected to host rul02 port 5903
CConnection: Server supports RFB protocol version 3.8
CConnection: Using RFB protocol version 3.8
CConn: Using pixel format depth 24 (32bpp) little-endian rgb888
CConn: Using Tight encoding
CConn: Enabling continuous updates
javax.net.ssl.SSLException: Unsupported record version Unknown-101.190
	at sun.security.ssl.InputRecord.checkRecordVersion(Unknown Source)
	at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(Unknown Source)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(Unknown Source)
	at sun.security.ssl.SSLEngineImpl.unwrap(Unknown Source)
	at javax.net.ssl.SSLEngine.unwrap(Unknown Source)
	at com.tigervnc.network.SSLEngineManager.read(SSLEngineManager.java:132)
	at com.tigervnc.rdr.TLSInStream.readTLS(TLSInStream.java:93)
	at com.tigervnc.rdr.TLSInStream.overrun(TLSInStream.java:76)
	at com.tigervnc.rdr.InStream.check(InStream.java:39)
	at com.tigervnc.rdr.InStream.check(InStream.java:46)
	at com.tigervnc.rdr.InStream.check(InStream.java:47)
	at com.tigervnc.rdr.InStream.readS8(InStream.java:57)
	at com.tigervnc.rdr.InStream.readU8(InStream.java:66)
	at com.tigervnc.rfb.CMsgReader.readMsg(CMsgReader.java:63)
	at com.tigervnc.rfb.CConnection.processMsg(CConnection.java:136)
	at com.tigervnc.vncviewer.VncViewer.run(VncViewer.java:565)
	at java.lang.Thread.run(Unknown Source)
com.tigervnc.rdr.TLSException: readTLS
	at com.tigervnc.rdr.TLSInStream.readTLS(TLSInStream.java:98)
	at com.tigervnc.rdr.TLSInStream.overrun(TLSInStream.java:76)
	at com.tigervnc.rdr.InStream.check(InStream.java:39)
	at com.tigervnc.rdr.InStream.check(InStream.java:46)
	at com.tigervnc.rdr.InStream.check(InStream.java:47)
	at com.tigervnc.rdr.InStream.readS8(InStream.java:57)
	at com.tigervnc.rdr.InStream.readU8(InStream.java:66)
	at com.tigervnc.rfb.CMsgReader.readMsg(CMsgReader.java:63)
	at com.tigervnc.rfb.CConnection.processMsg(CConnection.java:136)
	at com.tigervnc.vncviewer.VncViewer.run(VncViewer.java:565)
	at java.lang.Thread.run(Unknown Source)

**Comment by CendioOssman** [comment]
Could you install wireshark and get us a package dump from one of these failed connections?

TLS needs to be disabled though, or we won't be able to make sense of the data.

**Comment by CendioOssman** [comment]
No activity in quite some time. Closing.
