### ISSUE TITLE
vncserver exits if client disconnects?

### ISSUE THREAD

**Issue by pauledd** [TigerVNC/tigervnc#895]
Hi
On my RaspberryPi I have installed 
`tigervnc-standalone-server/stable,now 1.9.0+dfsg-3 armhf`

I start it with 
`vncserver -geometry 1000x800 -localhost no -fg`
I connect to it with vncviewer. As soon as I disconnect from the server, the server
terminates with this output:
```
vncserver -geometry 1000x800 -localhost no -fg                 

New 'rp:1 (pi)' desktop at :1 on machine rp

Starting applications specified in /etc/X11/Xvnc-session
Log file is /home/pi/.vnc/rp:1.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /home/pi/.vnc/passwd rp:1 to connect to the VNC server.


vncserver: Failed command '/etc/X11/Xvnc-session': 256!

=================== tail -15 /home/pi/.vnc/rp:1.log ===================
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
 VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian rgb888
terminate called after throwing an instance of 'rdr::EndOfStream'
terminate called recursively
(EE) 
(EE) Backtrace:
(EE) 
(EE) 
Fatal server error:
(EE) Caught signal 6 (Aborted). Server aborting
(EE) 
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":1"
      after 337 requests (336 known processed) with 0 events remaining.
Killing Xtigervnc process ID 14181... which seems to be deadlocked. Using SIGKILL!
Killing Xtigervnc process ID 14181... which seems to be deadlocked. Using SIGKILL!

=======================================================================

Starting applications specified in /etc/X11/Xvnc-session has failed.
Maybe try something simple first, e.g.,

```
I want vncserver to stay active after client disconnect. I did not specify the "autokill" switch, why does it kill anyway?

**Comment by CendioOssman** [comment]
I'm afraid this sounds like #800 which turned out to be a bug in the system libunwind. If so then there isn't much we can do about it. :/

Are you familiar with gdb? If so then we can try to confirm that this is the case.

**Comment by pauledd** [comment]
Sure, a little bit. I guess I need to attach to a process? 
Those are the ones running after starting vncserver containing "vnc":

```
ps aux | grep vnc
pi       22256  9.8  4.5 170744 43372 pts/0    Sl   14:07   0:00 /usr/bin/Xtigervnc :1 -desktop rp:1 (pi) -auth /home/pi/.Xauthority -geometry 1000x800 -depth 24 -rfbwait 30000 -rfbauth /home/pi/.vnc/passwd -rfbport 5901 -pn -SecurityTypes VncAuth,TLSVnc
pi       22257  0.0  0.6  14912  6184 pts/0    S    14:07   0:00 /usr/bin/perl /usr/bin/vncserver -geometry 1000x800 -localhost no
pi       22258  0.0  0.0   1940   396 pts/0    S    14:07   0:00 /bin/sh /etc/X11/Xvnc-session
pi       22259  0.8  0.5  13372  5408 pts/0    S    14:07   0:00 vncconfig -iconic
```

**Comment by CendioOssman** [comment]
Alright. So do this to get gdb to attach:

```
$ gdb -p 22256
```

Then we need it to trigger on some important lines:

```
(gdb) break VNCSConnectionST.cxx:169
(gdb) break FdInStream.cxx:214 if n == 0
(gdb) continue
```

Hopefully it should then stop once the bug is triggered. Then you can tell it to give a backtrace:

```
(gdb) bt full
(gdb) continue
```

Let's see what that says.

**Comment by pauledd** [comment]
Well. of cause this did not run as expected :)

The part until continue:
```
Attaching to process 591
[New LWP 618]
[New LWP 619]
[New LWP 620]
[New LWP 621]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
0x7647d9d0 in epoll_wait (epfd=<optimized out>, events=0x7e822318, maxevents=256, timeout=548230)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
30      ../sysdeps/unix/sysv/linux/epoll_wait.c: Datei oder Verzeichnis nicht gefunden.
(gdb) break VNCSConnectionST.cxx:169
No source file named VNCSConnectionST.cxx.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (VNCSConnectionST.cxx:169) pending.
(gdb) break FdInStream.cxx:214 if n == 0
No source file named FdInStream.cxx.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 2 (FdInStream.cxx:214 if n == 0) pending.
(gdb) continue
Continuing.
```
Then the SIGABRT signal if client disconnects and backtrace:
```
Thread 1 "Xtigervnc" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 0, 1986946680, 1995451568, 1985745104, 1995400400, 0, 1, 0, 2122457436, 1995328084, 1995412432, 1, 
            5, 0, 0, 1995178504, 0, 2069144, 1986103196, 2122457440, 78, 274877907, 0, 1995352900, 2069144, 1986784464, 8}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x763bd230 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x1d, sa_sigaction = 0x1d}, sa_mask = {__val = {1983561612, 1995437472, 29, 1986784292, 
              1983969208, 1984892144, 1512, 1984883484, 1986945184, 1995451568, 1985745104, 1995400400, 0, 1, 0, 1, 1995328084, 
              1995412432, 1, 5, 0, 1984892144, 1983561612, 1, 38860904, 1986945024, 38864672, 2226444, 274877907, 39384240, 1995352900, 
              29}}, sa_flags = 0, sa_restorer = 0x1}
        sigs = {__val = {32, 0 <repeats 31 times>}}
#2  0x766178fc in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
No symbol table info available.
#3  0x766155b0 in ?? () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
No symbol table info available.
#4  0x76615624 in std::terminate() () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
No symbol table info available.
#5  0x766159dc in __cxa_rethrow () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
No symbol table info available.
#6  0x766178b4 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
No symbol table info available.
#7  0x766155b0 in ?? () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
No symbol table info available.
#8  0x76615624 in std::terminate() () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
No symbol table info available.
#9  0x76615990 in __cxa_throw () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
No symbol table info available.
#10 0x0017827c in rdr::FdInStream::readWithTimeoutOrCallback(void*, int, bool) ()
No symbol table info available.
#11 0x001784ec in rdr::FdInStream::overrun(int, int, bool) ()
No symbol table info available.
#12 0x00162bb8 in rfb::VNCSConnectionST::processMessages() ()
No symbol table info available.
#13 0x001401fc in XserverDesktop::handleSocketEvent(int, network::SocketServer*, bool, bool) ()
No symbol table info available.
#14 0x00140310 in XserverDesktop::handleSocketEvent(int, bool, bool) ()
No symbol table info available.
#15 0x001e1c90 in ospoll_wait ()
No symbol table info available.
#16 0x001da880 in WaitForSomething ()
No symbol table info available.
#17 0x00190ba4 in Dispatch ()
No symbol table info available.
#18 0x00194fb0 in dix_main ()
No symbol table info available.
#19 0x763bd718 in __libc_start_main (main=0x7e823594, argc=1984888832, argv=0x763bd718 <__libc_start_main+268>, init=<optimized out>, 
    fini=0x1ee8c0 <__libc_csu_fini>, rtld_fini=0x76ee54c4 <_dl_fini>, stack_end=0x7e823594) at libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {-163908678, -24964826, 0, 2025568, 392500, 0, 0, 0, 1995464704, 0 <repeats 18 times>, 
                1995328084, 1995424624, 1, 1, 0, 35618160, 1983587228, 2122462448, 1995030528, 2220992, 19, 2122462612, 2122462692, 1995030224, 
                1995352900, 1994957648, 0, 296, 0, 2122462612, 1994854496, 2122462692, 0, 1994362632, 779095040, 0, 1995030224, 1994854400, 19, 
                2122462612, 2122462692, 1995030224, 1995464704, 1995178868, 1995330216, 0, 1995467128}, mask_was_saved = 0}}, priv = {pad = {0x0, 
              0x0, 0x76f06000, 0x76ee53ec <_dl_init+112>}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1995464704}}}
        not_first_call = <optimized out>
#20 0x0005fd60 in _start ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) c
Continuing.

Thread 1 "Xtigervnc" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      in ../sysdeps/unix/sysv/linux/raise.c
(gdb) q
A debugging session is active.

        Inferior 1 [process 591] will be detached.

Quit anyway? (y or n) y
Detaching from program: /usr/bin/Xtigervnc, process 591
[Inferior 1 (process 591) detached]
```
Looks like no debugging symbol included?

**Comment by CendioOssman** [comment]
It actually turned out well enough anyway. And that backtrace does confirm that it is some bug in libunwind (or libstdc++), like #800. So I'm afraid there isn't anything we can do about it in TigerVNC. :/

Please talk to Debian or glibc and see if they can provide some fix here.

**Comment by huapox** [comment]
+1 with aarch64, ubuntu20.04
---
but how to resolve?

**Comment by huapox** [comment]
resolved:  (ubuntu20.04-arm64, tigervnc12.0-source-compile/tigervnc10.0-apt-install)

```bash
#old
exec Xvnc  -ac $DISPLAY -listen tcp -rfbauth=/etc/xrdp/vnc_pass -depth 16 -BlacklistThreshold=3 -BlacklistTimeout=1

#new
LD_PRELOAD=/lib/aarch64-linux-gnu/libgcc_s.so.1 exec Xvnc  -ac $DISPLAY -listen tcp -rfbauth=/etc/xrdp/vnc_pass -depth 16 -BlacklistThreshold=3 -BlacklistTimeout=1
```
